name: einstein_app
description: "Торговый терминал Эйнштейн для Bybit V5"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Управление состоянием (Мосты UI)
  provider: ^6.1.2
  
  # Локальная база данных
  hive_ce: ^2.1.1
  hive_ce_flutter: ^2.1.1
  path_provider: ^2.1.3
  
  # Сетевой слой и логирование
  dio: ^5.5.0.2
  crypto: ^3.0.3
  logger: ^2.3.0
  
  # Системные утилиты, даты и фоновый режим
  intl: ^0.19.0
  timezone: ^0.9.4
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.1
  flutter_foreground_task: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
